name: Android Build and Release

on:
  push:
    # tags:
    #   - v*

jobs:
  release:
    runs-on: ubuntu-latest
    # ÈÖçÁΩÆÁéØÂ¢É
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # ‰∏ãÊãâ‰ªìÂ∫ì
      - name: Check out repository code
        uses: actions/checkout@v3
      # ‰∏ãËΩΩ Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      # ‰∏ãËΩΩ Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - name: List files in the repository
        run: |
          echo '' > ./assets/release.txt
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
      - run: flutter --version
      - run: java -version
      # ‰∏ãËΩΩ‰æùËµñ
      - name: Install dependencies
        run: flutter pub get
      # ÊûÑÂª∫
      - run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const latestRelease = releases[0];
            console.log(JSON.stringify(latestRelease, null, 2));
            return latestRelease;
      # ÂèëÂ∏ÉÂà∞ Release
      - name: Upload Release Android
        id: upload-release-android 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
